### ISSUE TITLE
Stubby wouldn't compile

### ISSUE THREAD

**Issue by tomdoyle87** [juzam/docker-getdns-stubby#1]
Hi, 

Dockerfile was unable to compile stubby this evening, fix:

Change:

RUN git checkout develop && git submodule update --init && libtoolize -ci && autoreconf -fi && mkdir build
To:
RUN git checkout master && git submodule update --init && libtoolize -ci && autoreconf -fi && mkdir build

Wouldn't it make more sense to default to master, being as development is unstable by nature?

Thanks Tom.

**Comment by juzam** [comment]
I think I'll stick with the `develop` branch of the getdns source code, even if it can occasionally generate a situation like this. In fact that is the default branch referenced by the Stubby docs https://github.com/getdnsapi/stubby#download-the-getdns-source 

If it's missing some libraries or parameters then I'll gladly fix like I did in this commit (see https://github.com/juzam/docker-getdns-stubby/commit/5eb3a7a7b5e4c4ebc3c074ec615c98fbe0437275 ) but, as I wrote, I'd like to leave the rest untouched.

This said, feel free to fork :)
Thanks for opening this issue.

**Comment by tomdoyle87** [comment]
Hi, 

The error seemed to be related to tls 1.3 (I can reproduce if required, forget to capture the error; was more concerned about getting up and running again). So I think  libssl-dev (or opensll) probably just needs to be pulled from buster/sid, or maybe disable tls 1.3 with a flag for now. 

Tom.

**Comment by juzam** [comment]
> The error seemed to be related to tls 1.3 (I can reproduce if required, forget to capture the error; was more concerned about getting up and running again). So I think libssl-dev (or opensll) probably just needs to be pulled from buster/sid, or maybe disable tls 1.3 with a flag for now.

I see, this is interesting. I'd very much like to have tls 1.3 support, If you can easily reproduce, that would help. Thank you.

**Comment by tomdoyle87** [comment]
Here you go:

```
make[1]: Entering directory '/getdns/build/src'
../libtool --quiet --tag=CC --mode=compile gcc -I../../src -I. -I../../src/util/auxiliary -I../../src/../stubby/src -g -O2 -Wall -Wextra -D_BSD_SOURCE -D_DEFAULT_SOURCE   -Wpedantic -c ../../src/const-info.c -o const-info.lo
../libtool --quiet --tag=CC --mode=compile gcc -I../../src -I. -I../../src/util/auxiliary -I../../src/../stubby/src -g -O2 -Wall -Wextra -D_BSD_SOURCE -D_DEFAULT_SOURCE   -Wpedantic -c ../../src/convert.c -o convert.lo
In file included from ../../src/convert.c:50:0:
../../src/util-internal.h: In function '_getdns_tls_version2openssl_version':
../../src/util-internal.h:229:29: error: 'TLS1_3_VERSION' undeclared (first use in this function)
  case GETDNS_TLS1_3: return TLS1_3_VERSION;
                             ^~~~~~~~~~~~~~
../../src/util-internal.h:229:29: note: each undeclared identifier is reported only once for each function it appears in
Makefile:122: recipe for target 'convert.lo' failed
make[1]: *** [convert.lo] Error 1
make[1]: Leaving directory '/getdns/build/src'
Makefile:53: recipe for target 'default' failed
make: *** [default] Error 2
The command '/bin/sh -c ../configure --without-libidn --without-libidn2 --enable-stub-only --with-stubby && make && make install && ldconfig' returned a non-zero code: 2
```
I think it needs OpenSSL 1.1.1, stretch has OpenSSL 1.1.0.

Thanks Tom.

**Comment by juzam** [comment]
closed via https://github.com/juzam/docker-getdns-stubby/pull/2

As you have correctly guessed the newer openssl package version `1.1.1a-1` from Debian Buster did the trick.

Now the develop branch compiles fine.

Thank you.

**Comment by tomdoyle87** [comment]
Hi, 

If you want to use tls 1.3, quad9 doesn't support it yet. Should consider changing upstream servers to cloudflare. 

Stubby YML:

```
dns_transport_list:
  - GETDNS_TRANSPORT_TLS

tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 128

edns_client_subnet_private: 1
idle_timeout: 10000
round_robin_upstreams: 1

listen_addresses:
  - 0::1@8053
upstream_recursive_servers:
  - address_data: 1.1.1.1
    tls_auth_name: "cloudflare-dns.com"
  - address_data: 1.0.0.1
    tls_auth_name: "cloudflare-dns.com"
```

tcpdump confirmed tls 1.3

Thanks Tom. 

P.S

Just had a closer look at the TCPDUMP, its using 1.3 as the protocol, but falling back to 1.2 for the exchange. Will update when I've worked out whats going on.

**Comment by tomdoyle87** [comment]
openssl in buster is aware of tls 1.3, but its not enabled. I compiled openssl with tls 1.3 enabled and was able to connect to cloudflares dns resolver with 1.3 s-client. But when using stubby still defaults to 1.2, even tried another 1.3 resolver, but still didn't work. Doesn't look like 1.3 is prime time yet, but if you do get anywhere with this would be interested to know. 

Thanks Tom.
